### ISSUE TITLE
无法判断会员卡对应装备的积攒次数

### ISSUE THREAD

**Issue by movef4-zz** [encoderlee/OpenFarmer#2]
比如木头会员卡可以使电锯多积攒两次，那一共就是3次，脚本的逻辑只判断了倒计时就去收割
![image](https://user-images.githubusercontent.com/72405847/148645093-6d934b7e-8943-4c83-8130-cd8cf92668fe.png)

**Comment by MaxLiuFW** [comment]
我在这借楼问个问题，我看到另外一个类似脚本，https://github.com/lintan/OpenFarmerOnAnchor   和咱们是啥关系呢？

**Comment by encoderlee** [comment]
现在已经支持了，更新一下
