### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by DekaSKy** [encoderlee/OpenFarmer#3]
Hello,sir can you add eng translation pls?

**Comment by jirapatr** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/4018473/152951274-f6f04ff9-7285-4146-81b3-f2cadc4be359.png)

You can edit source code to translate.

**Comment by DekaSKy** [comment]
> ![Screenshot_6](https://user-images.githubusercontent.com/4018473/152951274-f6f04ff9-7285-4146-81b3-f2cadc4be359.png)
> 
> You can edit source code to translate.

Can you send the translation? Or how can I contact Rindaman?

**Comment by encoderlee** [comment]
sorry,  we don't have time to process it, you can use google translate keywords  in  file 'dialog.py '
