### ISSUE TITLE
我看到另外一个openfarmaer脚本， 和咱们是啥关系呢？

### ISSUE THREAD

**Issue by MaxLiuFW** [encoderlee/OpenFarmer#4]
我在这借楼问个问题，我看到另外一个类似脚本，https://github.com/lintan/OpenFarmer   和咱们是啥关系呢？

**Comment by rimble65** [comment]
你链接的这个脚本说了 他的是根据你提issue的这个脚本改的

**Comment by encoderlee** [comment]
这是群里的兄弟在我的版本上持续更新和维护的版本
