### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by orangentle1** [encoderlee/OpenFarmer#6]
你好 这个脚本有运行的时候会有3个图标在任务栏 我有15个号 意味着我要开45个图标在任务栏里 非常麻烦 请问可不可以只用一个图标就解决一个号运行 谢谢！！

**Comment by encoderlee** [comment]
多开的话，最好不要用WAX云钱包账号，很麻烦的，稳定性也不好，最好用Anchor钱包来创建WAX原生账号，然后用命令行版本来运行，这样不依赖Chrome浏览器，一个进程一个窗口

下面是群友修改的版本，使用Anchor钱包创建WAX原生账号运行
https://github.com/lintan/OpenFarmerOnAnchor
