### ISSUE TITLE
关于打包

### ISSUE THREAD

**Issue by brunostreleraugherty** [encoderlee/OpenFarmer#8]
请问您我该如何打包成.exe文件，我尝试过pyinstaller打包，但是打包都没法正常运行，打包出来的文件跟您releases版本里面的内容有差别，并没有生成您的releases的那么多文件，您可以给个完整的打包流程吗？不甚感谢！

我打包完成之后，点击exe文件运行，出现下面错误：
failed to execute script 'pyi_rth_win32api' 

我的python版本：3.10.4
我的pyinstaller版本：4.10
打包命令：pyinstaller -F gui.spec

**Comment by encoderlee** [comment]
问题已在群里解决
